# Site settings
author: Natasha N. Waller
title: What In The World Was I Thinking?
header-img: img/home-bg.png
email: nnwaller@gmail.com
copyright_name: Natasha N. Waller
description: > # this means to ignore newlines until "baseurl:"
  Reflections Along My Coding Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  NNWaller

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
